"""expenses, medicines, staff salary

Revision ID: 59ff14062317
Revises: f87c39b9cb57
Create Date: 2026-07-06 03:14:59.379195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ff14062317'
down_revision: Union[str, None] = 'f87c39b9cb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_hospital_id'), 'expenses', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_expenses_spent_on'), 'expenses', ['spent_on'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_hospital_id'), 'medicines', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_table('medicine_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('restock', 'open_packet', 'use', 'adjust', name='medicine_log_action'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_logs_hospital_id'), 'medicine_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_medicine_logs_medicine_id'), 'medicine_logs', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_medicine_logs_patient_id'), 'medicine_logs', ['patient_id'], unique=False)
    op.add_column('memberships', sa.Column('designation', sa.String(length=80), nullable=True))
    op.add_column('memberships', sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'monthly_salary')
    op.drop_column('memberships', 'designation')
    op.drop_index(op.f('ix_medicine_logs_patient_id'), table_name='medicine_logs')
    op.drop_index(op.f('ix_medicine_logs_medicine_id'), table_name='medicine_logs')
    op.drop_index(op.f('ix_medicine_logs_hospital_id'), table_name='medicine_logs')
    op.drop_table('medicine_logs')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_hospital_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_expenses_spent_on'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_hospital_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
